Add  buildProperties to project service configuration (#383)
* Add buildArgs to service configuration and capture build configuration as global property to setup msbuild project

* Fix format

* Fix - Error CS8600: Converting null literal or possible null value to non-nullable type.

* Improve configuration format for build arguments

* Fix whitespace format

* Fix error CS8618: Non-nullable property 'Properties' is uninitialized. Consider declaring the property as nullable.

* Fix error CS8601: Possible null reference assignment.

* Translate non first class properties as /p:{Key}={Value} into the build command

* Fix property translation

* All properties are used to create the msbuild project

* Change the name (to BuildProperties) and the type (to List<BuildProperty>) of ConfigService property to load build properties

* Add support of build properties when tye run with --docker option

* Fix ComprehensionalTest

* Add tests to verify the output directory for the corresponding build configuration

* Fix whitespace format

* Override the correct CreateTestCasesForTheory to fix error CS0618

* Remove the usage of BuildPropertiesToOptionsMap and fix the code format